name: Deploy Dependency Scan App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy on EC2 Server
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/demo

          git pull origin main

          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "GITHUB_TOKEN=${{ secrets.DEPLOY_GITHUB_TOKEN }}" >> .env
          echo "GITHUB_APP_ID=${{ secrets.DEPLOY_GITHUB_APP_ID }}" >> .env
          echo "GITHUB_APP_SLUG=${{ secrets.DEPLOY_GITHUB_APP_SLUG }}" >> .env
          echo "GITHUB_WEBHOOK_SECRET=${{ secrets.DEPLOY_GITHUB_WEBHOOK_SECRET }}" >> .env
          echo "GITHUB_PRIVATE_KEY='${{ secrets.DEPLOY_GITHUB_PRIVATE_KEY }}'" >> .env

          docker stop dependency-scan-container || true
          docker rm dependency-scan-container || true

          docker build -t dependency-scan-app .

          docker run -d --name dependency-scan-container --env-file .env -p 127.0.0.1:5000:5000 dependency-scan-app

          docker image prune -f
        EOF
